apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minioconsole
  namespace: minio
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vault.k.erushnikov.ru
      secretName: wildcard-k-erushnikov-ru
  rules:
    - host: "minio.k.erushnikov.ru"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: console
                port:
                  name: http