apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

helmCharts:
- includeCRDs: true
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  version: 75.15.2
  valuesFile: ../../base/values.yaml
  additionalValuesFiles:
    - values.yaml

patches:
- path: ../../base/crd-argocd-replace.yaml