prometheus:
  prometheusSpec:
    externalLabels:
      cluster: infra
    retention: 30d
    enableAdminAPI: true
    volumes:
      - name: federate-basic-auth
        secret:
          secretName: federate-basic-auth
    volumeMounts:
      - name: federate-basic-auth
        mountPath: /etc/prometheus/secrets/federate-basic-auth
        readOnly: true
    additionalScrapeConfigs:
      - job_name: 'federate-dev'
        scrape_interval: 60s
        metrics_path: '/federate'
        scheme: https
        honor_labels: true
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/federate-basic-auth/password
        params:
          'match[]':
            - '{__name__=~".+"}'
        static_configs:
          - targets:
              - 'prometheus.dst.dev.icvr.xyz'

      - job_name: 'federate-test'
        scrape_interval: 60s
        metrics_path: '/federate'
        scheme: http  # Istio handles mTLS
        honor_labels: true
        params:
          'match[]':
            - '{__name__=~".+"}'
        static_configs:
          - targets:
              - test-prometheus.kube-prometheus-stack:9090

      - job_name: 'federate-stage'
        scrape_interval: 60s
        metrics_path: '/federate'
        scheme: https
        honor_labels: true
        basic_auth:
          username: prometheus
          password_file: /etc/prometheus/secrets/federate-basic-auth/password
        params:
          'match[]':
            - '{__name__=~".+"}'
        static_configs:
          - targets:
              - 'prometheus.dst.stage.icvr.xyz'