k8s_masters:
  hosts:
    # Control nodes
    control1.k.erushnikov.ru:
    control2.k.erushnikov.ru:
    control3.k.erushnikov.ru:
k8s_workers:
  hosts:
    # Worker nodes
    worker1.k.erushnikov.ru:
    worker2.k.erushnikov.ru:
    worker3.k.erushnikov.ru:
    db1.k.erushnikov.ru:
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
