apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/KErushnikov/k8s'
              revision: master
              directories:
                - path: "k.erushnikov/*/overlays/*"
                  exclude: false
                - path: "k.erushnikov/consul/overlays/*"
                  exclude: true
                - path: "k.erushnikov/vault/overlays/*"
                  exclude: true
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  kubernetes.io/environment: '{{ .path.basename }}'

  template:
    metadata:
      name: "{{ index .path.segments 1 }}-{{ .path.basename }}"
      labels:
        app: "{{ index .path.segments 1 }}"
        env: "{{ .path.basename }}"
    spec:
      project: "default"
      source:
        repoURL: 'https://github.com/KErushnikov/k8s'
        targetRevision: master
        path: "{{ .path.path }}"
      destination:
        server: "{{ .server }}"
        namespace: "{{ index .path.segments 1 }}"
      syncPolicy:
        # automated:
        #   selfHeal: true
        #   prune: true
        syncOptions:
          - CreateNamespace=true