apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  local.json: |
    {
      "backend": {
        "file": {
          "path": "/vault/data/core"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": 1
        }
      },
      "ui": true
    }