apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  local.json: |
    {
      "storage": {
        "file": {
          "path": "/vault/data"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      },
      "disable_mlock": true,
      "ui": true,
      "api_addr": "https://vault.k.erushnikov.ru"
    }