apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  serviceName: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      securityContext:
        fsGroup: 1005
        runAsUser: 1005
        runAsGroup: 1005
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1005:1005 /vault/data"]
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
      containers:
        - name: vault
          image: hashicorp/vault:1.16
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                {
                  "storage": {
                    "file": {
                      "path": "/vault/data"
                    }
                  },
                  "listener": {
                    "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": 1
                    }
                  },
                  "ui": true
                }
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
          securityContext:
            allowPrivilegeEscalation: false
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data-pvc