apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- cmp-plugin.yaml

patches:
- path: argocd-repo-server.yaml