apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/linux-factory/terraform/selectel/project1"
type: Opaque
stringData:
  TF_VAR_SELECTEL_SERVICE_USER: <TF_VAR_SELECTEL_SERVICE_USER>
  TF_VAR_SELECTEL_USER: <TF_VAR_SELECTEL_USER>