apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  labels:
    app: kafka
    env: test
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: kafka/kafka-art
    repoURL: 'https://github.com/KErushnikov/k8s'
    targetRevision: master
    helm:
      valueFiles:
        - values-k2.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
