victoria-metrics-agent:
  replicaCount: 1
  image:
    repository: victoriametrics/vmagent
    tag: "v1.72.0"
    pullPolicy: IfNotPresent

  nameOverride: "vmagent-sys"
  fullnameOverride: "vmagent-sys"

  rbac:
    ## If true, create & use RBAC resources
    ##
    create: true
    ## If true, create & use Pod Security Policy resources
    ## https://kubernetes.io/docs/concepts/policy/pod-security-policy/
    pspEnabled: false

  # Это параметр зависит от установки victoriametrics
  remoteWriteUrls:
    - http://victoriametrics-victoria-metrics-single-server:8428/api/v1/write

  service:
    enabled: true
    servicePort: 8429
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod

    extraLabels: { }
    hosts:
      - name: vmagent.k.erushnikov.ru
        path: /
        port: http
    tls:
      - secretName: "wildcard-k-erushnikov-ru"
        hosts:
          - vmagent.k.erushnikov.ru
    pathType: Prefix
    ingressClassName: traefik

  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 600Mi

    persistentVolume:
      enabled: false  # disables chart-generated PVC
    extraVolumes:
      - name: vmagent-storage
        persistentVolumeClaim:
          claimName: vm-data-pvc

  config:
    global:
      scrape_interval: 10s

  extraScrapeConfigs:
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [ __meta_kubernetes_endpoints_name ]
          regex: 'nexporter-prometheus-node-exporter'
          action: keep
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: [ 'ksm-kube-state-metrics.monitoring.svc.cluster.local:8080' ]
