ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: grafana.k.erushnikov.ru
      paths:
      - path: /
        pathType: Prefix
  tls:
    - hosts:
      - grafana.k.erushnikov.ru
      secretName: wildcard-k-erushnikov-ru

grafana:
  rbac:
    create: true
    ## Use an existing ClusterRole/Role (depending on rbac.namespaced false/true)
    # useExistingRole: name-of-some-(cluster)role
    pspEnabled: false
    pspUseAppArmor: false
    namespaced: false
  
  initChownData:
    ## If false, data ownership will not be reset at startup
    ## This allows the prometheus-server to be run with an arbitrary user
    ##
    enabled: false

  revisionHistoryLimit: 3
  testFramework:
    enabled: false
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    type: pvc
    enabled: true
    existingClaim: vm-data-pvc
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Victoria
        type: prometheus
        url: http://victoriametrics-victoria-metrics-single-server:8428
        access: proxy
        isDefault: true
