apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  labels:
    app: monitoring
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring/charts/alertmanager
    repoURL: 'https://github.com/KErushnikov/k8s'
    targetRevision: master
    helm:
      valueFiles:
        - my-values.yaml
  project:  monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
