victoria-metrics-single:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  server:
    retentionPeriod: 6h
    extraArgs:
      selfScrapeInterval: "15s"
      loggerLevel: "INFO"
    persistentVolume:
      enabled: true  # disables chart-generated PVC
      storageClass: local-path
      size: 2Gi
      mountPath: /PVC/vm
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: "500m"
        memory: 1Gi
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      hosts:
        - name: "vm.k.erushnikov.ru"
          path: /
          port: http
      tls:
        - secretName: "wildcard-k-erushnikov-ru"
          hosts:
            - vm.k.erushnikov.ru
      ingressClassName: traefik
    statefulSet:
      enabled: true
      podManagementPolicy: Parallel
    scrape:
      enabled: false

