victoria-metrics-single:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  server:
    retentionPeriod: 6h
    extraArgs:
      selfScrapeInterval: "15s"
      loggerLevel: "INFO"
    persistentVolume:
      enabled: false  # disables chart-generated PVC
    extraVolumes:
      - name: vm-data
        persistentVolumeClaim:
          claimName: vm-data-pvc
    resources:
      requests:
        cpu: 200m
        memory: 500Mi
      limits:
        cpu: "1"
        memory: 2Gi
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      hosts:
        - name: "vm.k.erusnikov.ru"
          path: /
          port: http
      tls:
        - secretName: "wildcard-k-erushnikov-ru"
          hosts:
            - vm.k.erusnikov.ru
      ingressClassName: traefik
    statefulSet:
      enabled: true
      podManagementPolicy: Parallel
    scrape:
      enabled: false

