apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  labels:
    app: default
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/KErushnikov/k8s'
    targetRevision: master
    path: vaultwarden/manifests
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true