apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: personal
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/KErushnikov/k8s'
    targetRevision: master
    path: vaultwarden/manifests
  project: personal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true