apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application
spec:
  ingressClassName: system-ingress
  rules:
  - host: app.k.erusnikov.ru
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
           name: application
           port:
             name: http
