apiVersion: batch/v1
kind: Job
metadata:
  name: vaultwarden-restore
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: untar
          image: alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Untarring vaultwarden backup..."
              tar -xzf /data/vaultwarden_data_backup.tar.gz -C /data && \
              echo "Removing archive..." && \
              rm /data/vaultwarden_data_backup.tar.gz && \
              echo "Done."
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data