apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: vaultwarden-pv  # binds directly to PV
  resources:
    requests:
      storage: 1Gi