apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: vaultwarden-pv
  storageClassName: ""  # 👈 Must match PV
  resources:
    requests:
      storage: 1Gi